name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-API:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./OnTrackAPI

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  build-react:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./webapp

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: webapp/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    
